title = "Multirotor design"

# List of folder paths where user added custom registered OpenMDAO components
module_folders = ["models"]

# Input and output files
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

# Definition of problem driver assuming the OpenMDAO convention "import openmdao.api as om"
driver = "om.ScipyOptimizeDriver(tol=1e-6, optimizer='SLSQP')"

# Definition of OpenMDAO model
[model]
    [model.sizing_scenarios]
        id = "multirotor.sizing_scenarios"
    [model.propeller]
        id = "multirotor.propeller"
    [model.motor]
        id = "multirotor.motor"
    [model.battery_and_esc]
        id = "multirotor.battery_and_esc"
    [model.frame]
        id = "multirotor.frame"
    [model.mission]
        id = "multirotor.mission"
    # [model.mtow]
    #     id = "multirotor.mtow"
    [model.system_constraints]
        id = "multirotor.system_constraints"
